apiVersion: v2
name: pagopacruscottobackend
description: Microservice description
type: application
version: 0.180.0
appVersion: 0.7.60
dependencies:
  - name: microservice-chart
    version: 7.5.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
