apiVersion: v2
name: pagopacruscottobackend
description: Microservice description
type: application
version: 0.211.0
appVersion: 0.9.0-1-dev
dependencies:
  - name: microservice-chart
    version: 7.5.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
