apiVersion: v2
name: pagopacruscottobackend
description: Microservice description
type: application
version: 0.188.0
appVersion: 0.8.3-1-releases/21-novembre
dependencies:
  - name: microservice-chart
    version: 7.5.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
